### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gituserfirst** [betweenbrain/Email-Additional-Fields#1]
Hello,

Is it possible to incluce a document on how to use your plugin in Joomla?

**Comment by betweenbrain** [comment]
Hello,

Yes, I sure can. I'll update this issue when I have something to show.

**Comment by gituserfirst** [comment]
I have on quick question if it possible to answer it. I upload the zip file successfully in Joomla admin console and I can see it in the plugin manager. After that I want to use the form in an article back I can't find a way to inser the plugin in the article so the article have the form. Should I make anything additional in order to run it?

**Comment by betweenbrain** [comment]
Hello,

This plugin does not add any fields to forms. It instead includes in the email all data from fields added to the core contact form when using a custom plugin like that described at http://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin.

Without this plugin, if you add fields to the core contact form, the data submitted in those fields are not included in the email that you recieve.

Hope this helps!

**Comment by betweenbrain** [comment]
I have added basic information from this issue to a readme. Please let me know if you have additional questions that can be answered.
