### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by robwent** [betweenbrain/Email-Additional-Fields#2]
I've got my extra fields into the contact form and have installed and enabled this plugin but I'm still not getting the info through in the email.

Everything look slike it should still work. Are there any gotchas with the forms that would stop anything getting added? My email just contains the standard message

**Comment by betweenbrain** [comment]
Can you provide details about the version of Joomla that you are using and about the extra fields themselves  (e.g. type)?

I am not aware of any gotchas and this is still working on the sites it was originally developed for.

**Comment by robwent** [comment]
Hi Matt,
Joomla 3.3.6

I've made a content plugin that uses onContentPrepareForm to lookout for the contact form and load fields from an xml file.

In the template override the fields are loaded in default_fom.php with 

```
<?php //Dynamically load any additional fields from plugins. ?>
        <?php foreach ($this->form->getFieldsets() as $fieldset) : ?>
            <?php if ($fieldset->name != 'contact'):?>
                <?php $fields = $this->form->getFieldset($fieldset->name);?>
                <?php foreach ($fields as $field) : ?>
                    <div class="form-group">
                        <?php if ($field->hidden) : ?>
                            <?php echo $field->input;?>
                        <?php else:?>
                            <?php echo preg_replace($lbreg, '" ' . $label, $field->label); ?>
                            <div class="col-sm-10">
                            <?php if (!$field->required && $field->type != "Spacer") : ?>
                            <?php endif; ?>
                            <?php echo preg_replace($regex, $input, $field->input);?>
                            </div>
                        <?php endif;?>
                    </div>
                <?php endforeach;?>
            <?php endif ?>
        <?php endforeach;?>
```

The fields show up in the form and validation seems to be working if custom required fields aren't filled in but nothing seems to come through in the mail.

You can see the form at: http://testserver.projektmanagement-zentrum.ch/einclusion.ch/de/mitglieder/mitglieder/3-sample-member-2.html

Can't for the life of me work it out...

**Comment by betweenbrain** [comment]
Hello Robert,

I've just tested the plugin with Joomls 3.3.36 and it works fine for me with a custom form plugin. To troubleshoot, I'd add something like the following to after `plugins/contact/emailadditionalfields/emailadditionalfields.php:30`:

```
JFactory::getApplication()->enqueueMessage('<pre>' . print_r($data, true) . '</pre>');
```

This will display the data being submitted for processing and should help you determine what is available to the plugin for processing.

Hope that helps!

**Comment by robwent** [comment]
strange, I just tried that but the message is just showing the standard thanks for the mail message, the data isn't getting added. So I guess the plugin isn't running even though it's enabled.

**Comment by robwent** [comment]
.....hadn't uploaded the file, doh.
Info seems to be there

```
Array
(
[contact_name] => Robert Went
[contact_email] => i@robertwent.com
[contact_custom] => Array
    (
        [contact_company] => Robert Went
        [contact_street] => 15 Exeter Close
        [contact_zip] => le12 6ls
        [contact_town] => Loughborough
        [contact_country] => Leicestershire
    )

[contact_subject] => ergeg
[contact_message] => tshsrt  
)
```

I guess it's because it's a multi-dimensional array

**Comment by robwent** [comment]
If I dump it just before the data is returned I get this, but the contect of the email that arrives doesn't contain the same message

```
Array
(
[contact_name] => Robert Went
[contact_email] => i@robertwent.com
[customfields] => Array
    (
        [contact_company] => Robert Went
        [contact_street] => 15 Exeter Close
        [contact_zip] => le12 6ls
        [contact_town] => Loughborough
        [contact_country] => Leicestershire
    )

[contact_subject] => debug test
[contact_message] => tykdtkContact_company: Robert Went
Contact_street: 15 Exeter Close
Contact_zip: le12 6ls
Contact_town: Loughborough
Contact_country: Leicestershire
)
```

**Comment by betweenbrain** [comment]
It does appear as if everything is working correctly.

'$data[contact_message]` is the contents of the email that is sent to the recipient. If you disable this plugin, that should change when dumping it just before the data is returned.

In my local test, the `$data` array looks like the following before getting processed by the plugin:

```
Array
(
    [contact_name] => Sam Bodee
    [contact_email] => sam@betweenbrain.com
    [contact_subject] => Testing
    [contact_message] => Hello Mum!
    [customfields] => Array
        (
            [recipients] => 1:bar
            [telephone] => 123-456-7891
            [company] => Boddee Co
            [address1] => 123 Main Street
            [address2] => 
            [city] => Samville
            [country] => Select the Country
            [state] => 
            [zip] => 
            [brand] => KAYE Validation and Environmental Monitoring
            [solutions] => CO2 Transmitters and Modules
        )

)
```

and after:

```
Array
(
    [contact_name] => Sam Bodee
    [contact_email] => sam@betweenbrain.com
    [contact_subject] => Testing
    [contact_message] => Hello Mum!Recipients: 1:bar
Telephone: 123-456-7891
Company: Boddee Co
Address1: 123 Main Street
Address2: 
City: Samville
Country: Select the Country
State: 
Zip: 
Brand: KAYE Validation and Environmental Monitoring
Solutions: CO2 Transmitters and Modules
    [customfields] => Array
        (
            [recipients] => 1:bar
            [telephone] => 123-456-7891
            [company] => Boddee Co
            [address1] => 123 Main Street
            [address2] => 
            [city] => Samville
            [country] => Select the Country
            [state] => 
            [zip] => 
            [brand] => KAYE Validation and Environmental Monitoring
            [solutions] => CO2 Transmitters and Modules
        )

)
```

The email received is:

> This is an enquiry email via http://localhost/dev/joomla/3-3/ from:
> Sam Bodee sam@betweenbrain.com
> 
> Hello Mum!Recipients: 1:bar
> Telephone: 123-456-7891
> Company: Boddee Co
> Address1: 123 Main Street
> Address2:
> City: Samville
> Country: Select the Country
> State:
> Zip:
> Brand: KAYE Validation and Environmental Monitoring
> Solutions: CO2 Transmitters and Modules

I'm wondering if something is going on around `components/com_contact/controllers/contact.php:165-177` after the plugin has passed the data back.

**Comment by robwent** [comment]
If I add the same debug line to the sendmail function then the message is the original.
If I add the same foreach loop directly in the sendmail function then the data comes through in the message.
I'm stumped...

**Comment by betweenbrain** [comment]
That is very strange and exactly how this plugin came about. I had that loop in the sendmail function until I discovered the seemingly undocumented, at that time, `onSubmitContact` plugin event.

Is this a clean install of Joomla? If not, it may be worth trying it with one to see if you have a different outcome. Not sure what it would be, but might provide another piece to the puzzle.

**Comment by robwent** [comment]
It's updated from a 2.5 site.

I just tried replacing all the core files but will test out now on a fresh install.
I checked all other plugins but couldn't see anything that might be affecting it.

**Comment by betweenbrain** [comment]
I look forward to learning of your results. I doubt any other plugins use this event, but another could possibly be filtering the email body contents.

**Comment by robwent** [comment]
The same thing is happening for me with a fresh install with normal testing data
http://testserver.projektmanagement-zentrum.ch/testsite/index.php/single-contact

only the standard message is coming through

**Comment by betweenbrain** [comment]
If you dump `$data`, can you see that `contact_message` is being changed to include the contents of the custom fields? Could there be some security measure on the server inspecting the contents of the emails being sent?

**Comment by robwent** [comment]
If I dump it in the plugin then the message is changed, but if I dump after the plugin event in the contact component then it's like the changed $data doesn't make it back.
It's a standard siteground hosting account. I'll try and test somewhere else

```
Array
(
[contact_name] => Robert Went
[contact_email] => shtr@sth.sh
[contact_subject] => rsth
[contact_message] => rth
Contact_company: 
Contact_street: Coach House, Rosemount
Contact_zip: ls73nx
Contact_town: Chapel Allerton
Contact_country: United Kingdom
[customfields] => Array
    (
        [contact_company] => 
        [contact_street] => Coach House, Rosemount
        [contact_zip] => ls73nx
        [contact_town] => Chapel Allerton
        [contact_country] => United Kingdom
    )

)
Array
(
[contact_name] => Robert Went
[contact_email] => shtr@sth.sh
[contact_subject] => rsth
[contact_message] => rth
[customfields] => Array
    (
        [contact_company] => 
        [contact_street] => Coach House, Rosemount
        [contact_zip] => ls73nx
        [contact_town] => Chapel Allerton
        [contact_country] => United Kingdom
    )

)
```

**Comment by robwent** [comment]
I'm getting the same behaviour locally as well.

**Comment by betweenbrain** [comment]
Would either of you be able to upload a copy of your form plugin somewhere so that I can test with it?

**Comment by robwent** [comment]
I'll mail you a zip

**Comment by betweenbrain** [comment]
Hello,

I've been testing this and can't see any issue with the plugin. I can confirm this with @robwent's plugin, and with https://github.com/betweenbrain/Custom-Contact-Form-Plugin, I am getting:

```
Hello
Company: betweenbrain llc.
Street:
City:
Zip:
Country: United States
```

**Comment by robwent** [comment]
how bizarre!

I'll test on a fresh install

**Comment by betweenbrain** [comment]
I may have finally pinpointed the issue. Can you please try version 1.0.2 at https://github.com/betweenbrain/Email-Additional-Fields/releases/tag/1.0.2

**Comment by robwent** [comment]
YES! Genius :)

I would never have seen that. I thought the & was something that existed in 1.5 all over the place and had now been removed.

For reference, the site is using php 5.5.17

Thank a lot!

**Comment by betweenbrain** [comment]
Fantastic, glad it's working well! It slipped past me too for a while.

**Comment by betweenbrain** [comment]
PS: This has been submitted to the JED - http://extensions.joomla.org/extensions/extension/contacts-and-feedback/forms/emai-additional-fields. Reviews, and feature requests here as new issues, are always warmly welcomed.

**Comment by robwent** [comment]
Ah, I didn't realize :) I thought you were going to submit it to the core. 1 Review coming up

**Comment by betweenbrain** [comment]
Thanks.

Submitting it to core is a good idea. I don't see where a few good reviews will hurt that ;-)
