### ISSUE TITLE
no additional infos in email

### ISSUE THREAD

**Issue by jojo12** [betweenbrain/Email-Additional-Fields#4]
Hi I installed your both plugins custom contact form and email additional fields.
I had others infos too, but did not get any additional fields in the email.

**Comment by betweenbrain** [comment]
Hello,

Others have reported similar issues, but I have not been able to reproduce them nor have my clients that this was developed for. Is it possible for me to test this directly, or for you to upload a backup of the site, generated with Akeeba Backup, for me to test?

**Comment by jojo12** [comment]
sorry, I can't but will look more into it.

**Comment by betweenbrain** [comment]
Thank you. Please update this issue when you have had a chance to do so.

**Comment by jojo12** [comment]
Oh, I saw, I should at least say in which version I am: Joomla! 3.4.1   php 5.4.36-0+deb7u3  
and db 5.5.40-0+wheezy1 

The additional fields of your form plugin is working fine! I even changed it for my purposes.
Only the transmission of the additional infos with email doesn't work

And the only working information I found in https://www.youtube.com/watch?v=uQzb7vfZSJI with creating a hack of the original files (this is working fine).

**Comment by betweenbrain** [comment]
I'm glad that the form plugin is working fine. For resources on how to create one, you can visit:
- https://docs.joomla.org/Plugin/Events/Content#onContentPrepareForm
- http://officialjoomlabook.com/elin-waring-official-joomla-book-blog/making-a-form-plugin

As well as look at the core user profile plugin at https://github.com/joomla/joomla-cms/tree/staging/plugins/user/profile

If there is anyway for me to get a copy of, or test directly, the site that you are experiencing the issue with, I would appreciate it. I  have not been able to reproduce this issue, as well as that of others are reporting.

**Comment by betweenbrain** [comment]
Closing as we have another issue to track this
