### ISSUE TITLE
translations?

### ISSUE THREAD

**Issue by jojo12** [betweenbrain/Email-Additional-Fields#7]
Hi,
it seems, the email sends the "field name" like hardcoded (with first letter as capital) and then the content filled in. I can live with that.

But the field name is not translated, not in english not in e.g. german.
So I have different things:
- a field name in form.xml
- a label  with a key like PLG_CONTENT_CUSTOMCONTACTFORMS_FIELD_...
- the translated label in the frontend form.
- only the field name in email.

Do you know something about using the translated labels in the email?

**Comment by betweenbrain** [comment]
Hello,

This is an interesting idea. The labels in the email are ones that I am adding in this plugin based on the field names.

Since there is no way of knowing the other plugin that is adding the fields to the form (this plugin just gets an array of data to work with), it may be possible to support dynamically named language strings using a language override of this plugin.

For example, if you are adding a form field named "city" I may be able to render that label with the language string of `PLG_CONTACT_EMAILADDITIONALFIELDS_FIELD_CITY`, where all fields would be named starting with `PLG_CONTACT_EMAILADDITIONALFIELDS_FIELD_`.

What do you think?

**Comment by jojo12** [comment]
Hi,
I think, it's more complicated and perhaps impossible:
in the mail is not the label and then the content  of the field
it's the field name and then the content
I don't know, if you can use keys for the field name. If yes, the the language override could work.
e.g.
            <field name="company"              <--this is in the email
                   type="text"
                   id="contact-company"
                   class="form-control"
                   size="30"
                   label="PLG_CONTENT_CUSTOMCONTACTFORMS_FIELD_COMPANY"
                   filter="string"
                    />

**Comment by betweenbrain** [comment]
Unfortunately, I don't think we can use language strings for the form field definitions for the custom form fields. At least, I've never seen anyone do that and was unsuccessful when just testing that.

**Comment by jojo12** [comment]
Yes, I think so. So it's important to know, that you have to give the additional fields clear names. And perhaps even in your own language.

**Comment by betweenbrain** [comment]
Do you think it's too confusing to add custom strings to an override for `en-GB.plg_contact_emailadditionalfields.ini`? I could likely code this to fallback to the field name if the dynamic language string is empty.

**Comment by jojo12** [comment]
I don't understand, so I can not help you, sorry

**Comment by betweenbrain** [comment]
Hello,

I have just committed a change that implements the ability to use language constants. To use this feature, you need to define a language override that follows the convention `PLG_CONTACT_EMAILADDITIONALFIELDS_[FIELD NAME]` where `[FIELD NAME]` is the all uppercase name of the form field. For example, if my form field name is `city`, then the language string is `PLG_CONTACT_EMAILADDITIONALFIELDS_CITY`.

You can get a copy of this version to test at https://github.com/betweenbrain/Email-Additional-Fields/releases/tag/1.1.0.

Can you please test this and report back?

Thanks!

**Comment by jojo12** [comment]
Sorry, I was some days away and then I didn't see your email.
Did download your beta and installed.
Did try like you wrote (until now only with City, but this works best. Witll test more!
Wow!

**Comment by betweenbrain** [comment]
Thank you for testing!!!

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by jojo12** [comment]
Congratulations! All is working well, even in my own form.

**Comment by betweenbrain** [comment]
Fantastic, thanks again for testing. I'll move this toward a release.
